; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf

; Velocidade do Monitor Serial (Padrão da ESP-IDF)
monitor_speed = 115200

; Filtros para o monitor serial (ajuda a ver logs coloridos da IDF)
monitor_filters = direct, esp32_exception_decoder

; Força o compilador a tratar avisos como erros (Boa prática de nível Júnior)
build_flags = 
    -Wall
    -Werror